name: gymnasium-env
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pytorch
  # - torchvision
  # - torchaudio
  - pytorch-cuda=12.1 
  - pip
  - pip:
      - gymnasium
      - pygame
      - box2d
      - tqdm
      - matplotlib
      - stable-baselines3[extra]
      - sb3_contrib
      # - git+https://github.com/Stable-Baselines-Team/stable-baselines3-contrib.git@refs/pull/287/head#egg=sb3_contrib
      # - git+https://github.com/akbaig/stable-baselines3-contrib.git
      - -e ./stable-baselines3-contrib
      - tensorboard  
      - torchinfo
      - transformers
      # - git+https://github.com/wdlctc/recurrent_maskable.git
